<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Terms of Service & Privacy Policy | eCollab</title>
<style>
:root{color-scheme:dark;--bg:#070b14;--card:#0e1728;--card2:#111d31;--line:#22314a;--text:#f8fafc;--muted:#9fb0c9;--pink:#e91e8c;--purple:#8b3df0}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top right,rgba(139,61,240,.12),transparent 34%),var(--bg);color:var(--text);font:14px/1.7 Inter,Arial,sans-serif}
.top{position:sticky;top:0;z-index:5;display:flex;align-items:center;justify-content:space-between;padding:16px max(20px,calc((100% - 1040px)/2));background:rgba(7,11,20,.94);border-bottom:1px solid var(--line);backdrop-filter:blur(12px)}
.brand{font-size:18px;font-weight:800}.brand span{color:#d946ef}.back{color:#dbeafe;text-decoration:none;border:1px solid var(--line);padding:7px 12px;border-radius:8px}
.wrap{max-width:1040px;margin:0 auto;padding:44px 20px 70px}.hero{padding:28px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(135deg,rgba(233,30,140,.09),rgba(139,61,240,.09));margin-bottom:22px}
h1{font-size:30px;margin:0 0 6px}h2{font-size:18px;margin:0 0 12px}h3{font-size:14px;margin:18px 0 5px}.muted,p,li{color:var(--muted)}.updated{font-size:12px;color:#c4b5fd}
.grid{display:grid;grid-template-columns:220px 1fr;gap:20px}.toc,.doc{border:1px solid var(--line);border-radius:14px;background:var(--card)}.toc{padding:15px;height:max-content;position:sticky;top:78px}.toc a{display:block;color:#b9c8df;text-decoration:none;padding:7px 8px;border-radius:6px}.toc a:hover{background:var(--card2);color:#fff}.doc{padding:26px}.section{padding:4px 0 22px;margin-bottom:22px;border-bottom:1px solid var(--line)}.section:last-child{border:0;margin:0}.notice{padding:12px 14px;border-left:3px solid var(--purple);background:rgba(139,61,240,.08);border-radius:6px;color:#cbd5e1}strong{color:#fff}a{color:#c084fc}
@media(max-width:760px){.grid{grid-template-columns:1fr}.toc{position:static}.wrap{padding-top:24px}.doc{padding:18px}}
</style>
</head>
<body>
<header class="top"><div class="brand"><span>◆</span> eCollab</div><a class="back" href="<?= htmlspecialchars(BASE_URL,ENT_QUOTES) ?>/modules/auth/signup.php">← Back to Sign Up</a></header>
<main class="wrap">
<section class="hero"><h1>Terms of Service & Privacy Policy</h1><div class="updated">Effective: September 24, 2026</div><p>These terms explain the rules for using eCollab and how personal information is handled. By creating or using an eCollab account, you agree to these Terms of Service and acknowledge this Privacy Policy.</p></section>
<div class="grid">
<nav class="toc"><strong>Contents</strong><a href="#terms">Terms of Service</a><a href="#accounts">Accounts</a><a href="#conduct">Acceptable Use</a><a href="#content">User Content</a><a href="#moderation">Moderation</a><a href="#privacy">Privacy Policy</a><a href="#data">Information We Process</a><a href="#use">How We Use Data</a><a href="#rights">Your Privacy Rights</a><a href="#security">Security</a><a href="#contact">Contact</a></nav>
<article class="doc">
<section class="section" id="terms"><h2>1. Terms of Service</h2><p>eCollab is a collaborative learning platform designed for students, facilitators, and authorized administrators. Features may include academic and community servers, channels, direct and group messaging, peer matching, voice sessions, Coworkspaces, whiteboards, polls, announcements, reports, and participation analytics.</p><p>Academic services intended for the College of Computer Studies of Our Lady of Fatima University – Antipolo may be restricted to authorized users and institutional accounts. Community features may permit eligible personal accounts.</p></section>
<section class="section" id="accounts"><h2>2. Accounts and Access</h2><p>You must provide accurate information when registering and keep your login credentials secure. You are responsible for activity performed through your account unless unauthorized access is reported. You must not impersonate another person, misuse another account, bypass authentication or access controls, or attempt to obtain privileges you are not authorized to have.</p><p>Roles such as student, facilitator, moderator, administrator, and server-specific roles may provide different permissions. Access to a server, channel, or Coworkspace does not grant permission to access information outside the privileges assigned to you.</p></section>
<section class="section" id="conduct"><h2>3. Acceptable Use</h2><p>Users must use eCollab for lawful academic, collaborative, and community purposes. The following are prohibited:</p><ul><li>harassment, bullying, threats, or abusive conduct;</li><li>spam, unauthorized advertising, or self-promotion;</li><li>phishing, scams, fraud, malware, or attempts to compromise accounts or systems;</li><li>posting unlawful, seriously inappropriate, or infringing material;</li><li>attempting to bypass server bans, suspensions, mutes, permissions, or other security controls;</li><li>unauthorized collection, disclosure, or misuse of another person's personal information;</li><li>disrupting eCollab infrastructure, exploiting vulnerabilities, or using the service to attack other systems.</li></ul></section>
<section class="section" id="content"><h2>4. Messages, Files and User Content</h2><p>You retain responsibility for content you submit, including messages, files, profile information, polls, whiteboards, and Coworkspace material. By submitting content, you permit eCollab to store, transmit, display, and process it as necessary to operate the features you choose to use. Do not upload material you do not have the right to share.</p><p>Visibility depends on the feature and selected permissions. Content in public areas may be visible to other eligible users, while private server, channel, direct-message, and Coworkspace content is limited according to applicable access controls.</p></section>
<section class="section" id="moderation"><h2>5. Reports and Moderation</h2><p>Users may report messages for reasons including <strong>spam or self-promotion, harassment or bullying, inappropriate content, phishing or scam, and other concerns</strong>. Reports may contain the reported message, reporter, reported user, reason, additional details, server, channel, status, and moderation outcome.</p><p>Authorized facilitators may moderate servers they own. Depending on the circumstances, actions may include a warning, deletion where supported, a temporary mute, temporary suspension, removal, or ban. A mute may prevent chat participation while a suspension may restrict the user to view-only access for the applicable server. A banned user may be prevented from rejoining that server until unbanned. Administrators may take additional actions required to protect the platform or enforce these terms.</p></section>
<section class="section"><h2>6. Availability and Changes</h2><p>eCollab is provided as an academic collaboration system and may change as features are developed. Availability is not guaranteed at all times. Features may be modified, restricted, suspended, or discontinued for maintenance, security, academic requirements, or system improvement.</p></section>
<section class="section" id="privacy"><h2>7. Privacy Policy</h2><div class="notice">eCollab intends to process personal data consistently with the Philippine Data Privacy Act of 2012 (Republic Act No. 10173), its implementing rules, and the principles of transparency, legitimate purpose, and proportionality.</div><p>This policy describes information processed when you register for and use eCollab. The exact data processed depends on the features you use and your role.</p></section>
<section class="section" id="data"><h2>8. Information We Process</h2><h3>Account and profile information</h3><p>This may include your name, username, email address, institutional affiliation, course/program, year level, profile details, hobbies, interests, goals, and skill-related information you provide.</p><h3>Authentication information</h3><p>eCollab processes information needed to authenticate accounts, including password credentials in protected form, verification status, login/session information, and information received from supported Google or Microsoft sign-in when you choose those methods.</p><h3>Activity and collaboration information</h3><p>This may include server and channel memberships, messages, threads, reactions, uploaded files, Coworkspace activity, whiteboards, polls, announcements, reports, participation information, and voice/study-session participation records needed for the feature.</p><h3>Technical and security information</h3><p>eCollab may process session, security, error, rate-limit, and similar technical records necessary to operate, troubleshoot, and protect the service.</p></section>
<section class="section" id="use"><h2>9. How Information Is Used</h2><p>Information may be processed to create and authenticate accounts; provide servers, messaging and collaboration tools; suggest relevant peers, rooms, or learning connections; operate facilitator and administrator functions; provide participation analytics; deliver notifications; investigate reports and enforce server/platform rules; maintain security; troubleshoot errors; and improve eCollab.</p><p>Peer-matching features may use profile information such as course, year level, interests, hobbies, goals, and skills to generate recommendations. Recommendations are intended to assist discovery and collaboration and do not guarantee compatibility or academic outcomes.</p></section>
<section class="section"><h2>10. Sharing and Visibility</h2><p>Personal information and content are made available only as needed for eCollab functionality and according to the visibility of the relevant profile, server, channel, Coworkspace, or feature. Facilitators may access information reasonably necessary to manage and monitor servers they are authorized to manage. Administrators may access information needed for security, support, moderation, reporting, and system administration.</p><p>Information may also be disclosed when required by applicable law or when reasonably necessary to protect users, the service, or legal rights. Third-party authentication or infrastructure providers process information according to their own applicable terms and privacy practices when their services are used.</p></section>
<section class="section"><h2>11. Data Retention</h2><p>Personal information should be retained only for as long as reasonably necessary for the purpose for which it was collected, legitimate academic or operational needs, security and moderation records, dispute resolution, or legal obligations. Retention periods may differ by data category. Data that is no longer required should be securely deleted, anonymized, or otherwise handled according to applicable requirements.</p></section>
<section class="section" id="rights"><h2>12. Your Privacy Rights</h2><p>Subject to applicable law, users may have rights concerning their personal data, including being informed about processing, requesting access, disputing inaccurate information and requesting correction, objecting to or withdrawing consent from certain processing where applicable, and lodging a complaint with the appropriate authority. Requests may be subject to identity verification and lawful exceptions.</p></section>
<section class="section" id="security"><h2>13. Security</h2><p>eCollab uses organizational and technical controls intended to protect information from unauthorized access, alteration, disclosure, loss, or misuse. These may include authentication controls, role and server permissions, CSRF protection, rate limiting, protected sessions, moderation controls, and access restrictions. No online service can guarantee absolute security, so users should also protect their credentials and report suspected compromise promptly.</p></section>
<section class="section"><h2>14. Account Restrictions and Termination</h2><p>Access may be limited or terminated when a user violates these terms, creates security or safety risks, repeatedly abuses platform features, or when access is no longer authorized. Server-specific moderation does not necessarily terminate the user's entire eCollab account unless a platform-level action is taken by an authorized administrator.</p></section>
<section class="section"><h2>15. Updates to These Terms</h2><p>These Terms and Privacy Policy may be updated as eCollab changes or as legal, academic, security, or operational requirements develop. Material changes should be communicated through an appropriate notice in the service. Continued use after an effective update constitutes acceptance where permitted by applicable law.</p></section>
<section class="section" id="contact"><h2>16. Contact and Privacy Requests</h2><p>Questions, account concerns, privacy requests, or reports about misuse should be submitted through eCollab's authorized support or administrative channels. Before production deployment, the project administrator should publish the official privacy/contact email and, where applicable, the identity or contact details of the responsible personal information controller or Data Protection Officer.</p><div class="notice"><strong>Project note:</strong> This document is a platform policy draft, not a substitute for review by OLFU, the project's responsible data controller, Data Protection Officer, or qualified legal counsel before production use.</div></section>
</article></div></main>
</body></html>