<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once ROOT_PATH.'/database/config/db.php';
require_once ROOT_PATH.'/security/middleware/AuthMiddleware.php';
AuthMiddleware::startSession();
$user=AuthMiddleware::requireAuth();$csrf=AuthMiddleware::csrfToken();
$serverId=(int)($_GET['server_id']??0);$channelId=(int)($_GET['channel_id']??0);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collabs – <?=htmlspecialchars(APP_NAME,ENT_QUOTES,'UTF-8')?></title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#0f1117;color:#f5f7fb;font-family:Inter,system-ui,sans-serif}.shell{max-width:1400px;margin:auto;padding:22px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px}.back{color:#aeb8ca;text-decoration:none}.brand h1{margin:7px 0 3px}.muted{color:#98a1b2}.layout{display:grid;grid-template-columns:230px 1fr;gap:18px;margin-top:20px}.panel{background:#171a23;border:1px solid #292e3b;border-radius:16px}.side{padding:15px;height:max-content}.label{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#7f899c;margin:6px 8px}.server{padding:7px 8px 18px;font-weight:700}.nav-item,.btn,.sort{width:100%;border:1px solid #303646;background:#141720;color:#cbd3e0;text-align:left;padding:10px 12px;border-radius:9px;cursor:pointer;margin:3px 0}.nav-item:hover,.nav-item.active,.btn:hover,.sort:hover{background:#252a38;color:#fff}.main{padding:25px}.title{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.title h2{margin:8px 0}.pill{display:inline-flex;align-items:center;padding:5px 9px;border-radius:999px;background:#252a38;color:#cbd3e0;font-size:11px}.green{color:#8ee6a8}.tabs,.toolbar{display:flex;gap:8px;margin:18px 0;flex-wrap:wrap}.tab{border:1px solid #303646;background:#141720;color:#cbd3e0;border-radius:9px;padding:8px 11px;cursor:pointer}.tab.active{background:#2b3140;color:#fff}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(245px,1fr));gap:15px}.card{border:1px solid #2d3340;background:#141720;border-radius:13px;overflow:hidden}.thumb{height:150px;background:#202534;display:grid;place-items:center;position:relative}.thumb-page{font-size:45px}.card-body{padding:12px}.doc-title{font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.meta{font-size:12px;color:#929caf;margin-top:6px}.actions{display:flex;gap:6px;margin-top:10px}.actions button{width:auto;margin:0}.empty,.notice{padding:35px;text-align:center;color:#9aa4b6;border:1px dashed #303646;border-radius:12px}.wb-wrap{height:calc(100vh - 190px);min-height:500px;display:flex;flex-direction:column}.wb-tools{display:flex;gap:8px;align-items:center;margin:12px 0}.wb-tools button{width:auto}.wb-canvas{flex:1;background:#fff;border-radius:12px;cursor:crosshair;touch-action:none}.modal-backdrop{display:none;position:fixed;inset:0;background:#0009;align-items:center;justify-content:center;z-index:50;padding:18px}.modal-backdrop.open{display:flex}.modal{background:#171a23;border:1px solid #303646;border-radius:14px;padding:20px;width:min(460px,100%)}.modal h3{margin-top:0}.setting{padding:10px 0;border-bottom:1px solid #292e3b}.danger{color:#ff9b9b}.right{margin-left:auto}@media(max-width:800px){.layout{grid-template-columns:1fr}.side{display:flex;overflow:auto;gap:5px}.side .label,.server{display:none}.nav-item{width:auto;white-space:nowrap}.main{padding:18px}}
</style><script src="<?=BASE_URL?>/assets/js/accessibility-apply.js" defer></script></head><body><div class="shell"><header class="top"><div class="brand"><a class="back" id="backToChat" href="<?=BASE_URL?>/modules/chat/chat.php">← Back to Chat</a><h1>🤝 Collabs</h1><span class="muted">Shared documents and whiteboard for this server.</span></div><span class="pill">👤 <?=htmlspecialchars((string)($user['full_name']?:$user['username']),ENT_QUOTES,'UTF-8')?></span></header><div class="layout"><aside class="panel side"><div class="label">Server</div><div id="serverName" class="server">Loading…</div><div class="label">Collabs</div><button class="nav-item active" id="documentsNav">📄 Documents</button><button class="nav-item" id="whiteboardNav">🖊 Whiteboard</button></aside><main class="panel main" id="detail"><div class="notice">Loading Coworkspace…</div></main></div></div>
<div id="settings" class="modal-backdrop" onclick="if(event.target===this)closeSettings()"><div class="modal"><h3>⚙ Coworkspace / document settings</h3><div class="setting"><small>Workspace</small><div id="setWorkspace"></div></div><div class="setting"><small>Visibility</small><div id="setVisibility">Controlled by Coworkspace membership.</div></div><div class="setting"><small>Editing</small><div id="setEditing">Loading…</div></div><div class="setting"><small>Document access</small><div>Members and roles are enforced by the Coworkspace.</div></div><div class="actions"><button class="btn" onclick="closeSettings()">Close</button></div></div></div>
<script>
const API='<?=BASE_URL?>/API/collaboration/server-coworkspaces.php',DOCS='<?=BASE_URL?>/API/collaboration/documents.php',DELETE_API='<?=BASE_URL?>/API/collaboration/delete-document.php',WB='<?=BASE_URL?>/API/collaboration/whiteboard.php',CSRF='<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>',SERVER_ID=<?=$serverId?>,CHANNEL_ID=<?=$channelId?>,BASE='<?=BASE_URL?>';
const state={server:null,workspace:null,docs:[],type:'docx',section:'documents',sort:'recent'};const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const icon=t=>t==='xlsx'?'📊':t==='pptx'?'📽':'📄';
async function getJson(u){const r=await fetch(u,{credentials:'same-origin'});const d=await r.json().catch(()=>({success:false,error:'Invalid response'}));if(!r.ok||!d.success)throw Error(d.error||'Request failed');return d}async function postJson(u,b){const r=await fetch(u,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':CSRF},body:JSON.stringify({...b,csrf_token:CSRF})});const d=await r.json().catch(()=>({success:false,error:'Invalid response'}));if(!r.ok||!d.success)throw Error(d.error||'Request failed');return d}
function typeName(t){return t==='xlsx'?'Excel':t==='pptx'?'PowerPoint':'Word'}function closeSettings(){document.getElementById('settings').classList.remove('open')}function openSettings(){document.getElementById('setWorkspace').textContent=state.server?.name||'—';document.getElementById('setEditing').textContent=state.workspace?.allow_edit_documents?'Enabled by workspace policy':'Disabled by workspace policy';document.getElementById('settings').classList.add('open')}
function renderDocs(){let docs=state.docs.filter(d=>d.file_type===state.type);if(state.sort==='recent')docs.sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at));else docs.sort((a,b)=>(b.presence?.total>0)-(a.presence?.total>0)||new Date(b.updated_at)-new Date(a.updated_at));document.getElementById('detail').innerHTML=`<div class="title"><div><span class="pill">📄 DOCUMENTS</span><h2>${esc(state.server.name)} · ${typeName(state.type)}</h2><span class="muted">Create, open, manage and delete Coworkspace documents.</span></div><button class="sort" style="width:auto" onclick="openSettings()">⚙ Settings</button></div><div class="tabs"><button class="tab ${state.type==='docx'?'active':''}" onclick="setType('docx')">📄 Word</button><button class="tab ${state.type==='xlsx'?'active':''}" onclick="setType('xlsx')">📊 Excel</button><button class="tab ${state.type==='pptx'?'active':''}" onclick="setType('pptx')">📽 PowerPoint</button></div><div class="toolbar"><button class="sort" style="width:auto" onclick="createDoc()">＋ New ${typeName(state.type)}</button><button class="sort" style="width:auto" onclick="state.sort=state.sort==='recent'?'live':'recent';renderDocs()">Sort: ${state.sort==='recent'?'Recent':'Live first'}</button></div>${docs.length?`<div class="grid">${docs.map(d=>`<article class="card"><div class="thumb"><div class="thumb-page">${icon(d.file_type)}</div></div><div class="card-body"><div class="doc-title">${esc(d.title)}</div><div class="meta">${esc(d.file_name)} · ${d.presence?.total||0} active</div><div class="actions"><button class="btn" onclick="openDoc('${esc(d.open_url)}')">Open</button><button class="btn" onclick="documentSettings(${d.id})">⚙</button><button class="btn danger" onclick="deleteDoc(${d.id})">🗑</button></div></div></article>`).join('')}</div>`:`<div class="empty"><h3>No documents yet</h3><p>Create the first ${typeName(state.type)} document.</p></div>`}`}
function documentSettings(id){const d=state.docs.find(x=>+x.id===+id);if(!d)return;document.getElementById('setWorkspace').textContent=state.server.name+' / '+d.title;document.getElementById('setEditing').textContent=state.workspace?.allow_edit_documents?'Enabled by workspace policy':'View only';document.getElementById('settings').classList.add('open')}
async function deleteDoc(id){if(!confirm('Delete this document permanently?'))return;try{await postJson(DELETE_API,{document_id:id,workspace_id:state.workspace.id});await refreshDocs()}catch(e){alert(e.message)}}
async function createDoc(){try{const d=await postJson(DOCS,{workspace_id:state.workspace.id,title:'Untitled '+typeName(state.type),type:state.type});location.href=d.document.open_url}catch(e){alert(e.message)}}function openDoc(u){location.href=u}function setType(t){state.type=t;renderDocs()}
let wbCanvas,ctx,drawing=false,strokes=[];function renderWhiteboard(){document.getElementById('detail').innerHTML=`<div class="title"><div><span class="pill">🖊 WHITEBOARD</span><h2>${esc(state.server.name)} Whiteboard</h2><span class="muted">Shared by Coworkspace members.</span></div><button class="sort" style="width:auto" onclick="openSettings()">⚙ Settings</button></div><div class="wb-wrap"><div class="wb-tools"><button class="btn" onclick="clearBoard()">Clear</button><button class="btn" onclick="saveBoard()">Save</button><span id="wbStatus" class="muted right">Loading…</span></div><canvas id="wbCanvas" class="wb-canvas"></canvas></div>`;setupCanvas();loadBoard()}
function setupCanvas(){wbCanvas=document.getElementById('wbCanvas');ctx=wbCanvas.getContext('2d');const resize=()=>{const r=wbCanvas.getBoundingClientRect();const old=document.createElement('canvas');old.width=wbCanvas.width;old.height=wbCanvas.height;if(wbCanvas.width&&wbCanvas.height)old.getContext('2d').drawImage(wbCanvas,0,0);wbCanvas.width=r.width*devicePixelRatio;wbCanvas.height=r.height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.lineWidth=2;ctx.lineCap='round';if(old.width)ctx.drawImage(old,0,0,old.width/devicePixelRatio,old.height/devicePixelRatio)};resize();addEventListener('resize',resize);const pos=e=>{const r=wbCanvas.getBoundingClientRect();return{x:(e.clientX-r.left),y:(e.clientY-r.top)}};wbCanvas.onpointerdown=e=>{drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);strokes.push([p.x,p.y])};wbCanvas.onpointermove=e=>{if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();strokes.push([p.x,p.y])};wbCanvas.onpointerup=()=>drawing=false;wbCanvas.onpointerleave=()=>drawing=false}
function clearBoard(){ctx.clearRect(0,0,wbCanvas.width/devicePixelRatio,wbCanvas.height/devicePixelRatio);strokes=[];saveBoard()}async function loadBoard(){try{const d=await getJson(WB+'?workspace_id='+state.workspace.id);if(d.state?.image){const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,wbCanvas.width/devicePixelRatio,wbCanvas.height/devicePixelRatio);im.src=d.state.image}document.getElementById('wbStatus').textContent=d.updated_at?'Last saved '+d.updated_at:'New board'}catch(e){document.getElementById('wbStatus').textContent=e.message}}async function saveBoard(){try{const image=wbCanvas.toDataURL('image/png');await postJson(WB,{workspace_id:state.workspace.id,state:{image}});document.getElementById('wbStatus').textContent='Saved just now'}catch(e){document.getElementById('wbStatus').textContent=e.message}}
async function refreshDocs(){try{const d=await getJson(DOCS+'?workspace_id='+state.workspace.id);state.docs=d.documents||[];if(state.section==='documents')renderDocs()}catch(e){console.warn(e)}}async function boot(){try{const q=SERVER_ID?'?server_id='+SERVER_ID:'?channel_id='+CHANNEL_ID;const d=await getJson(API+q);state.server=d.server;state.workspace=(d.workspaces||[])[0];if(!state.workspace)throw Error('The server Coworkspace could not be synchronized.');document.getElementById('serverName').textContent=state.server.name;document.getElementById('backToChat').href=BASE+'/modules/chat/chat.php?server_id='+state.server.id;await refreshDocs()}catch(e){document.getElementById('detail').innerHTML='<div class="notice">'+esc(e.message)+'</div>'}}
document.getElementById('documentsNav').onclick=()=>{state.section='documents';document.getElementById('documentsNav').classList.add('active');document.getElementById('whiteboardNav').classList.remove('active');renderDocs()};document.getElementById('whiteboardNav').onclick=()=>{state.section='whiteboard';document.getElementById('whiteboardNav').classList.add('active');document.getElementById('documentsNav').classList.remove('active');renderWhiteboard()};boot();setInterval(refreshDocs,10000);
</script></body></html>
