<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/config.php';
require_once ROOT_PATH . '/database/config/db.php';
require_once ROOT_PATH . '/security/middleware/AuthMiddleware.php';
require_once ROOT_PATH . '/services/CoworkspaceService.php';

AuthMiddleware::startSession();
$user = AuthMiddleware::requireAuth();
$db = Database::getInstance();
$workspaceId = (int)($_GET['workspace_id'] ?? 0);
$whiteboardId = (int)($_GET['whiteboard_id'] ?? 0);
$channelId = (int)($_GET['channel_id'] ?? 0);
if ($workspaceId < 1 || $whiteboardId < 1 || $channelId < 1) { http_response_code(400); exit('A Coworkspace whiteboard session is required.'); }
$uid = (int)$user['id'];
$workspace = CoworkspaceService::get($db, $workspaceId, $uid);
if (!$workspace) { http_response_code(403); exit('You do not have access to this Coworkspace.'); }
$stmt = $db->prepare('SELECT wb.id,wb.title,wb.description,wb.visibility,wb.public_permission,wb.created_by,cw.server_id,cw.channel_id,cw.host_id FROM collab_whiteboards wb INNER JOIN collab_workspaces cw ON cw.id=wb.workspace_id WHERE wb.id=:id AND wb.workspace_id=:wid LIMIT 1');
$stmt->execute([':id'=>$whiteboardId,':wid'=>$workspaceId]);
$board=$stmt->fetch(PDO::FETCH_ASSOC);
if(!$board){http_response_code(404);exit('Whiteboard session not found.');}
$serverId=(int)$board['server_id'];$workspaceChannelId=(int)$board['channel_id'];
if($serverId<1||$workspaceChannelId<1||$workspaceChannelId!==$channelId){http_response_code(400);exit('Invalid Coworkspace navigation context.');}
$isOwner=(int)$board['created_by']===$uid||(int)$board['host_id']===$uid;
$stmt=$db->prepare('SELECT permission FROM collab_resource_permissions WHERE resource_type="whiteboard" AND resource_id=:rid AND user_id=:uid LIMIT 1');$stmt->execute([':rid'=>$whiteboardId,':uid'=>$uid]);$explicitPermission=$stmt->fetchColumn();
$publicPermission=strtolower((string)($board['public_permission']??'view'));if(!in_array($publicPermission,['view','comment','edit'],true))$publicPermission='view';
$accessPermission=$isOwner?'edit':($explicitPermission!==false?strtolower((string)$explicitPermission):($board['visibility']==='public'?$publicPermission:'view'));if(!in_array($accessPermission,['view','comment','edit'],true))$accessPermission='view';
if(!$isOwner&&$board['visibility']==='private'&&$explicitPermission===false){http_response_code(403);exit('This private whiteboard has not been shared with you.');}
$csrf=AuthMiddleware::csrfToken();$title=(string)$board['title'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title,ENT_QUOTES,'UTF-8')?> – Whiteboard</title><meta name="csrf-token" content="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><script src="<?=BASE_URL?>/assets/js/accessibility-apply.js" defer></script><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/desktop/whiteboard.css"><link rel="stylesheet" href="<?=BASE_URL?>/assets/css/mobile/whiteboard-mobile.css"><style>
html,body{margin:0;height:100%;overflow:hidden;background:#0b0f1a}#wbOverlay{display:flex!important;position:relative!important;inset:auto!important;height:100vh!important}.wb-page-back{color:#94a3b8;text-decoration:none;font-size:12px;margin-right:8px;padding:5px 8px;border:1px solid transparent;border-radius:7px;transition:border-color .15s,background .15s,color .15s}.wb-page-back:hover{outline:1px solid rgba(168,85,247,.55);border-color:rgba(168,85,247,.35);background:rgba(168,85,247,.08);color:#fff}.wb-session-badge,.wb-permission-label{font-size:10px;color:#94a3b8;padding:4px 8px;border:1px solid rgba(255,255,255,.1);border-radius:999px;margin-right:8px}.wb-page-btn{height:30px;padding:0 10px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.06);color:#e2e8f0;border-radius:7px;cursor:pointer;font-size:11px}.wb-danger-btn{border-color:rgba(248,113,113,.35);color:#fca5a5}.wb-manage-modal{display:none;position:fixed;inset:0;z-index:300;background:#0009;align-items:center;justify-content:center;padding:18px}.wb-manage-modal.open{display:flex}.wb-manage-box{width:min(650px,100%);max-height:90vh;overflow:auto;background:#121826;border:1px solid rgba(255,255,255,.12);border-radius:14px;padding:20px;color:#e2e8f0}.wb-manage-box h3{margin:0 0 5px}.wb-manage-muted{color:#94a3b8;font-size:12px}.wb-manage-label{display:block;font-size:11px;color:#aeb8ca;margin:13px 0 5px}.wb-manage-input,.wb-manage-select{width:100%;box-sizing:border-box;background:#0b101b;color:#fff;border:1px solid #30394b;border-radius:8px;padding:10px}.wb-manage-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:16px;flex-wrap:wrap}.wb-danger-zone{margin-top:20px;padding-top:15px;border-top:1px solid rgba(248,113,113,.18)}.wb-danger-zone h4{color:#fca5a5;margin:0 0 5px}.wb-access-view .wb-tbtn:not([data-tool="cursor"]),.wb-access-comment .wb-tbtn:not([data-tool="cursor"]):not([data-tool="sticky"]){opacity:.35;pointer-events:none}.wb-access-view #wbCanvas{cursor:default!important}
</style></head><body class="wb-access-<?=htmlspecialchars($accessPermission,ENT_QUOTES,'UTF-8')?>"><div id="wbOverlay" class="wb-visible">
<div class="wb-hdr"><a class="wb-page-back" href="<?=BASE_URL?>/modules/collaboration/server-coworkspaces.php?server_id=<?=$serverId?>&channel_id=<?=$channelId?>">← Server Coworkspace</a><div class="wb-hdr-logo">&#9997;</div><div class="wb-hdr-titles"><div class="wb-hdr-title" id="wbBoardName"><?=htmlspecialchars($title,ENT_QUOTES,'UTF-8')?></div><div class="wb-hdr-sub"><?=htmlspecialchars((string)($board['description']??''),ENT_QUOTES,'UTF-8')?:'Independent Coworkspace session'?></div></div><div class="wb-hdr-center"><button class="wb-icon-btn" onclick="wbUndo()" title="Undo">↶</button><button class="wb-icon-btn" onclick="wbRedo()" title="Redo">↷</button><select class="wb-zoom-sel" id="wbZoom" onchange="wbSetZoom(this.value)"><option>50%</option><option>75%</option><option selected>100%</option><option>125%</option><option>150%</option></select></div><div class="wb-hdr-right"><span id="wbLockLabel" class="wb-lock-label"></span><span class="wb-permission-label"><?=strtoupper(htmlspecialchars($accessPermission,ENT_QUOTES,'UTF-8'))?> ACCESS</span><span class="wb-session-badge">Session #<?=$whiteboardId?></span><div class="wb-av-stack" id="wbAvStack"></div><?php if($accessPermission!=='view'):?><button class="wb-page-btn" onclick="wbSaveSessionNow()">Save</button><?php endif;?><?php if($isOwner):?><button class="wb-page-btn" onclick="wbOpenManage()">⚙ Access</button><?php endif;?></div></div>
<div class="wb-body"><div class="wb-tools"><button class="wb-tbtn wb-active" data-tool="cursor" onclick="wbPickTool(this)" title="Select / Cursor">&#9654;</button><button class="wb-tbtn" data-tool="pen" onclick="wbPickTool(this)" title="Pen">&#9998;</button><button class="wb-tbtn" data-tool="highlight" onclick="wbPickTool(this)" title="Highlighter">&#9644;</button><button class="wb-tbtn" data-tool="eraser" onclick="wbPickTool(this)" title="Eraser">&#9003;</button><div class="wb-tsep"></div><button class="wb-tbtn" data-tool="text" onclick="wbPickTool(this)" title="Text">T</button><button class="wb-tbtn" data-tool="sticky" onclick="wbPickTool(this)" title="Sticky Note">&#9632;</button><button class="wb-tbtn" data-tool="arrow" onclick="wbPickTool(this)" title="Arrow">&#8594;</button></div><div class="wb-canvas-wrap" id="wbCanvasWrap"><canvas id="wbCanvas"></canvas><div id="wbObjects"></div><div class="wb-bottom-bar"><div class="wb-clr sel" style="background:#a855f7" onclick="wbClr(this,'#a855f7')"></div><div class="wb-clr" style="background:#fff" onclick="wbClr(this,'#fff')"></div><div class="wb-clr" style="background:#22c55e" onclick="wbClr(this,'#22c55e')"></div><div class="wb-vsep"></div><button class="wb-sz-btn" onclick="wbSzDown()">-</button><span class="wb-sz-lbl" id="wbSzLbl">2px</span><button class="wb-sz-btn" onclick="wbSzUp()">+</button></div></div><div class="wb-rsidebar" id="wbRightSidebar"><div class="wb-tabs"><div class="wb-tab wb-tab-active" onclick="wbTab(this,'wbPanMembers')">Members</div><div class="wb-tab" onclick="wbTab(this,'wbPanActivity')">Activity</div></div><div class="wb-panel wb-panel-active" id="wbPanMembers"><div class="wb-section-lbl" id="wbMembersLabel">WHITEBOARD MEMBERS - 0</div><div id="wbMemberList"></div></div><div class="wb-panel" id="wbPanActivity"><div class="wb-section-lbl">ACTIVITY</div><div class="wb-activity" id="wbActivityLog"></div></div></div></div><div class="wb-status"><div class="wb-status-item">&#9679; <span id="wbSaveLabel">Loading session…</span></div><div class="wb-status-item" id="wbSessionStatus">Loading session…</div></div></div>
<?php if($isOwner):?><div id="wbManageModal" class="wb-manage-modal"><div class="wb-manage-box"><h3>Whiteboard access</h3><div class="wb-manage-muted">Manage this session just like a document resource.</div><label class="wb-manage-label">Title</label><input id="wbManageTitle" class="wb-manage-input" value="<?=htmlspecialchars($title,ENT_QUOTES,'UTF-8')?>"><label class="wb-manage-label">Description</label><input id="wbManageDescription" class="wb-manage-input" value="<?=htmlspecialchars((string)($board['description']??''),ENT_QUOTES,'UTF-8')?>"><label class="wb-manage-label">Visibility</label><select id="wbManageVisibility" class="wb-manage-select"><option value="public" <?=$board['visibility']==='public'?'selected':''?>>Public — Coworkspace members</option><option value="private" <?=$board['visibility']==='private'?'selected':''?>>Private — explicitly granted users</option></select><label class="wb-manage-label">Public permission</label><select id="wbManagePublicPermission" class="wb-manage-select"><option value="view" <?=$publicPermission==='view'?'selected':''?>>View</option><option value="comment" <?=$publicPermission==='comment'?'selected':''?>>Comment</option><option value="edit" <?=$publicPermission==='edit'?'selected':''?>>Edit</option></select><div class="wb-manage-actions"><button class="wb-page-btn" onclick="wbCloseManage()">Close</button><button class="wb-page-btn" onclick="wbSaveManage()">Save changes</button></div><div class="wb-danger-zone"><h4>Danger zone</h4><div class="wb-manage-muted">Deleting permanently removes this whiteboard session and its saved state.</div><div class="wb-manage-actions"><button class="wb-page-btn wb-danger-btn" onclick="wbDeleteSession()">🗑 Delete whiteboard</button></div></div></div></div><?php endif;?>
<script>window.ECOLLAB={baseUrl:<?=json_encode(BASE_URL)?>,csrfToken:<?=json_encode($csrf)?>,userId:<?=$uid?>,username:<?=json_encode($user['username'])?>,currentServerId:<?=$serverId?>,currentChannelId:<?=$channelId?>,workspaceId:<?=$workspaceId?>,whiteboardId:<?=$whiteboardId?>,whiteboardStandalone:true,whiteboardSessionMode:true,whiteboardPermission:<?=json_encode($accessPermission)?>,whiteboardIsOwner:<?=$isOwner?'true':'false'?>};window.__USER__={id:<?=$uid?>,username:<?=json_encode($user['username'])?>,fullName:<?=json_encode($user['full_name']??$user['username'])?>,role:<?=json_encode($user['role'])?>};window.__currentServerId=<?=$serverId?>;window.__currentChannelId=<?=$channelId?>;window.__currentWhiteboardId=<?=$whiteboardId?>;window.__currentWorkspaceId=<?=$workspaceId?>;function showToast(m){const e=document.getElementById('wbSessionStatus');if(e)e.textContent=m;}</script>
<script src="<?=BASE_URL?>/assets/js/chat/socket-core.js?v=wsfix7"></script><script src="<?=BASE_URL?>/assets/js/chat/whiteboard.js?v=wsfix7"></script><script>
(function(){const API=<?=json_encode(BASE_URL.'/API/collaboration/whiteboards.php')?>,ACCESS=<?=json_encode(BASE_URL.'/API/collaboration/resource-access.php')?>,WID=<?=$workspaceId?>,BID=<?=$whiteboardId?>,PERM=<?=json_encode($accessPermission)?>,IS_OWNER=<?=$isOwner?'true':'false'?>;let lastUpdated='',polling=null;const baseWbSend=window.wbSend;window.wbSend=function(p){if(!p)return false;if(p.whiteboard_id===undefined)p={...p,whiteboard_id:BID};return baseWbSend?baseWbSend(p):false;};const baseHandler=window.wbHandleWsMessage;if(baseHandler){const h=m=>{if(m&&m.whiteboard_id!=null&&Number(m.whiteboard_id)!==BID)return;baseHandler(m);};window.wbHandleWsMessage=h;if(window.__wsMsgHandlers){['wb_op','wb_cursor','wb_state','wb_joined','wb_peer_joined','wb_peer_left'].forEach(t=>window.__wsMsgHandlers[t]=h);}}
function req(url,method='GET',body=null){const o={method,credentials:'same-origin',headers:{'X-CSRF-Token':window.ECOLLAB.csrfToken}};if(body){o.headers['Content-Type']='application/json';o.body=JSON.stringify({...body,workspace_id:WID,whiteboard_id:BID,csrf_token:window.ECOLLAB.csrfToken});}return fetch(url,o).then(async r=>{const d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok||!d.success)throw Error(d.error||'Request failed');return d;});}
function wbReq(method,body){return req(API+'?workspace_id='+WID+'&whiteboard_id='+BID,method,body)}function accessReq(method,body){return req(ACCESS+'?workspace_id='+WID+'&resource_type=whiteboard&resource_id='+BID,method,body)}
window.wbSaveSessionNow=async()=>{if(!wbState.open||PERM==='view')return;try{const s={paths:wbState.paths||[],objects:wbState.objects?Object.keys(wbState.objects).map(k=>{const e=wbState.objects[k];return{id:k,x:parseFloat(e.style.left)||0,y:parseFloat(e.style.top)||0,text:e.textContent||''};}):[]};const d=await wbReq('POST',{action:'save',state:s});lastUpdated=d.updated_at||'';wbState.dirty=false;showToast('Saved just now');}catch(e){showToast('Save failed: '+e.message)}};
window.wbOpenManage=()=>document.getElementById('wbManageModal').classList.add('open');window.wbCloseManage=()=>document.getElementById('wbManageModal').classList.remove('open');
window.wbSaveManage=async()=>{try{const title=document.getElementById('wbManageTitle').value.trim(),description=document.getElementById('wbManageDescription').value.trim(),visibility=document.getElementById('wbManageVisibility').value,publicPermission=document.getElementById('wbManagePublicPermission').value;if(!title)return alert('A whiteboard title is required.');await wbReq('POST',{action:'rename',title,description});await accessReq('PATCH',{visibility,public_permission:publicPermission});document.getElementById('wbBoardName').textContent=title;showToast('Whiteboard access settings saved.');wbCloseManage();}catch(e){alert(e.message)}};
window.wbDeleteSession=async()=>{if(!confirm('Delete this whiteboard permanently?'))return;if(!confirm('This cannot be undone. Delete whiteboard #'+BID+'?'))return;try{await wbReq('POST',{action:'delete'});location.href=<?=json_encode(BASE_URL.'/modules/collaboration/server-coworkspaces.php?server_id='.$serverId.'&channel_id='.$channelId)?>;}catch(e){alert(e.message)}};
async function load(){try{const d=await wbReq('GET'),s=d.whiteboard.state||{paths:[],objects:[]};lastUpdated=d.whiteboard.updated_at||'';wbState.paths=Array.isArray(s.paths)?s.paths:[];wbState.objects={};wbState.dirty=false;wbState.isOwner=IS_OWNER;document.getElementById('wbBoardName').textContent=d.whiteboard.title||<?=json_encode($title)?>;document.getElementById('wbSaveLabel').textContent=PERM==='view'?'View only':'Saved just now';wbInitCanvas();wbState.open=true;wbUpdateMemberList();wbApplyFullState(JSON.stringify(s));document.body.classList.add('wb-access-'+PERM);document.querySelectorAll('.wb-tbtn').forEach(b=>{const t=b.dataset.tool;b.disabled=!(PERM==='edit'||(PERM==='comment'&&(t==='cursor'||t==='sticky'))||(PERM==='view'&&t==='cursor'));});polling=setInterval(async()=>{if(wbState.open&&!wbState.drawing&&!wbState.dirty){try{const x=await wbReq('GET');if(x.whiteboard.updated_at!==lastUpdated){lastUpdated=x.whiteboard.updated_at;wbApplyFullState(JSON.stringify(x.whiteboard.state||{paths:[],objects:[]}));}}catch(e){}}},2000);showToast('Session #'+BID+' ready');}catch(e){showToast('Could not load whiteboard: '+e.message)}}window.openWhiteboard=()=>{wbState.boardName=<?=json_encode($title)?>;wbState.whiteboardId=BID;wbState.sessionId=BID;wbState.channelId=<?=$channelId?>;wbState.open=true;load();};window.closeWhiteboard=()=>{if(wbState.open&&PERM!=='view')window.wbSaveSessionNow();wbState.open=false;if(polling)clearInterval(polling);location.href=<?=json_encode(BASE_URL.'/modules/collaboration/server-coworkspaces.php?server_id='.$serverId.'&channel_id='.$channelId)?>;};document.addEventListener('DOMContentLoaded',openWhiteboard);})();
</script></body></html>
