-- Extended eCollab user customization settings
-- Safe to run once on ecollab_v2.
ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS font_scale SMALLINT UNSIGNED NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS message_density VARCHAR(16) NOT NULL DEFAULT 'cozy',
  ADD COLUMN IF NOT EXISTS sidebar_scale SMALLINT UNSIGNED NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS typing_indicators TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS link_previews TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS media_previews TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS autoplay_gifs TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS show_timestamps TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS enter_to_send TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS notification_groups TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS notification_replies TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS notification_threads TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS notification_reactions TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS notification_connections TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS notification_announcements TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS camera_device VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS voice_mode VARCHAR(20) NOT NULL DEFAULT 'voice_activity',
  ADD COLUMN IF NOT EXISTS input_sensitivity SMALLINT UNSIGNED NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS jarred_enabled TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS jarred_response_style VARCHAR(20) NOT NULL DEFAULT 'balanced',
  ADD COLUMN IF NOT EXISTS jarred_personalization TINYINT(1) NOT NULL DEFAULT 1;
