<?php

declare(strict_types=1);
require_once dirname(__DIR__,2).'/database/config/db.php';
class WhiteboardHandler{
 private PDO $db;private array $rooms=[];private array $opLog=[];private array $stateCache=[];
 private const PALETTE=[['#3b82f6','#1d4ed8'],['#ec4899','#be185d'],['#14b8a6','#0f766e'],['#f59e0b','#b45309'],['#22c55e','#15803d'],['#6366f1','#4338ca'],['#ef4444','#b91c1c'],['#f97316','#c2410c']];
 public function __construct(){$this->db=Database::getInstance();}
 public function join(int $channelId,int $userId,string $username):array{$this->rooms[$channelId]??=[];$i=count($this->rooms[$channelId])%count(self::PALETTE);[$c1,$c2]=self::PALETTE[$i];$this->rooms[$channelId][$userId]=['user_id'=>$userId,'username'=>$username,'color'=>$c1,'grad'=>"linear-gradient(135deg,{$c1},{$c2})",'initial'=>mb_strtoupper(mb_substr($username,0,1))];$peers=[];foreach($this->rooms[$channelId] as $uid=>$p)if($uid!==$userId)$peers[]=$p;return ['type'=>'wb_joined','channel_id'=>$channelId,'peers'=>array_values($peers),'you'=>$this->rooms[$channelId][$userId],'state_json'=>$this->getState($channelId),'pending_ops'=>$this->opLog[$channelId]??[]];}
 public function leave(int $channelId,int $userId):array{if(!isset($this->rooms[$channelId]))return [];unset($this->rooms[$channelId][$userId]);if(empty($this->rooms[$channelId])){unset($this->rooms[$channelId]);unset($this->opLog[$channelId]);}return $this->getRoomUserIds($channelId);}
 public function getRoomUserIds(int $channelId,int $excludeId=0):array{return array_values(array_filter(array_keys($this->rooms[$channelId]??[]),fn($id)=>$id!==$excludeId));}
 public function getUserMeta(int $channelId,int $userId):?array{return $this->rooms[$channelId][$userId]??null;}
 public function getMembers(int $channelId):array{return array_values($this->rooms[$channelId]??[]);}
 public function canEdit(int $channelId,int $userId):bool{try{$stmt=$this->db->prepare('SELECT created_by,locked FROM whiteboards WHERE channel_id=:cid ORDER BY updated_at DESC LIMIT 1');$stmt->execute([':cid'=>$channelId]);$board=$stmt->fetch();return !$board||!(bool)$board['locked']||(int)$board['created_by']===$userId;}catch(\Throwable){return false;}}
 public function recordOp(int $channelId,int $userId,array $op):array{$meta=$this->rooms[$channelId][$userId]??[];$stamped=array_merge($op,['user_id'=>$userId,'username'=>$meta['username']??'','color'=>$meta['color']??'#a855f7','grad'=>$meta['grad']??'','initial'=>$meta['initial']??'?','ts'=>round(microtime(true)*1000)]);$opType=$op['op']??'';if($opType==='cursor')return $stamped;$this->opLog[$channelId]??=[];$this->opLog[$channelId][]=$stamped;if(count($this->opLog[$channelId])%20===0)$this->persistSnapshot($channelId,$userId);return $stamped;}
 private function replayOpsToState(int $channelId):string{$paths=[];$active=[];foreach($this->opLog[$channelId]??[] as $op){$type=$op['op']??'';$pathId=(string)($op['path_id']??'');if($type==='stroke_start'&&$pathId!==''){$active[$pathId]=['id'=>$op['path_id'],'tool'=>$op['tool']??'pen','color'=>$op['color']??'#000000','size'=>(float)($op['size']??2),'points'=>[['x'=>(float)($op['x']??0),'y'=>(float)($op['y']??0)]]];}elseif($type==='stroke_point'&&$pathId!==''&&isset($active[$pathId])){$active[$pathId]['points'][]=['x'=>(float)($op['x']??0),'y'=>(float)($op['y']??0)];}elseif($type==='stroke_end'&&$pathId!==''&&isset($active[$pathId])){$paths[]=$active[$pathId];unset($active[$pathId]);}elseif($type==='undo'&&isset($op['path_id'])){$id=(string)$op['path_id'];$paths=array_values(array_filter($paths,fn($p)=>(string)($p['id']??'')!==$id));unset($active[$id]);}elseif($type==='clear'){$paths=[];$active=[];}}foreach($active as $path)$paths[]=$path;return json_encode(['paths'=>array_values($paths)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
 public function persistSnapshot(int $channelId,int $userId,string $stateJson=''):void{$payload=$stateJson?:$this->replayOpsToState($channelId);try{$exists=$this->db->prepare('SELECT id FROM whiteboards WHERE channel_id=:cid ORDER BY updated_at DESC LIMIT 1');$exists->execute([':cid'=>$channelId]);$row=$exists->fetch();if($row)$this->db->prepare('UPDATE whiteboards SET state_json=:s,updated_by=:uid,updated_at=NOW() WHERE id=:id')->execute([':s'=>$payload,':uid'=>$userId,':id'=>$row['id']]);else$this->db->prepare('INSERT INTO whiteboards(channel_id,state_json,created_by,created_at,updated_at) VALUES(:cid,:s,:uid,NOW(),NOW())')->execute([':cid'=>$channelId,':s'=>$payload,':uid'=>$userId]);$this->stateCache[$channelId]=$payload;}catch(\Throwable $e){error_log('[WhiteboardHandler] DB error: '.$e->getMessage());}}
 public function getState(int $channelId):?string{if(isset($this->stateCache[$channelId]))return $this->stateCache[$channelId];try{$stmt=$this->db->prepare('SELECT state_json FROM whiteboards WHERE channel_id=:cid ORDER BY updated_at DESC LIMIT 1');$stmt->execute([':cid'=>$channelId]);$row=$stmt->fetch();if($row){$this->stateCache[$channelId]=$row['state_json'];return $row['state_json'];}}catch(\Throwable){}return null;}
}
