-- ============================================================
-- 015_seeds_v2.sql
-- ============================================================
-- NEUTRALIZED — this file's entire content (institutions,
-- academic_programs, users, user_profiles, interest_tags, servers,
-- channels, messages, and 25 more sections) was an earlier, buggier
-- draft of the exact same seed data that was later copy-pasted into
-- and evolved within 002_core_schema.sql's own embedded seed section.
-- This standalone file was left behind unedited when that happened,
-- and every explicit-id INSERT in it collides with the now-more-
-- complete, now-fixed version already seeded by 002_core_schema.sql
-- (e.g. its `users` section still has the exact same stray-extra-value
-- bug that was fixed in 002 — "(1, 1, 3, 'super_admin', ...)" — direct
-- confirmation this is a stale earlier copy, not independent content).
--
-- Verified before neutralizing: every one of this file's 32 sections
-- (institutions through system_settings) has a same-named counterpart
-- already present and fully seeded inside 002_core_schema.sql. No
-- unique data exists here that isn't already covered there.
--
-- Kept in the migrations/ directory (rather than deleted) so the
-- migration sequence numbering and the schema_migrations tracking
-- registry stay consistent with what's already been applied to any
-- existing database. If this project's real production database was
-- ever seeded via this file specifically (rather than via 002), its
-- data is already in place and this neutralized version changes
-- nothing further for it.
-- ============================================================

SET FOREIGN_KEY_CHECKS = 1;
