-- ============================================================
-- 016_seeds_chat.sql
-- ============================================================
-- NEUTRALIZED — this file's entire content (servers, server_members,
-- channels, messages, message_reactions, message_reads, whiteboards)
-- was the original source of a "CS Hub / IT Alpha / Study Lounge"
-- dataset that was separately copy-pasted into 002_core_schema.sql
-- (identical server names, channel structure, message text, reactions,
-- and whiteboard init). This standalone file was left behind unedited
-- when that happened.
--
-- Both this file's `servers` INSERT and the copy that was inside
-- 002_core_schema.sql use a `created_by` column that does not exist on
-- the real `servers` table (which requires `owner_id`, NOT NULL, FK'd
-- to users, and has no created_by column at all). The copy inside 002
-- was already identified as schema-incompatible and removed in favor
-- of a working "CS 305 / CS 201 / CS 210" dataset that correctly uses
-- owner_id. This file has the identical incompatibility and would fail
-- the same way if it ran on its own.
--
-- Kept in the migrations/ directory (rather than deleted) so the
-- migration sequence numbering and the schema_migrations tracking
-- registry stay consistent with what's already been applied to any
-- existing database.
-- ============================================================

SET foreign_key_checks = 1;
