<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once ROOT_PATH.'/database/config/db.php';require_once ROOT_PATH.'/security/middleware/AuthMiddleware.php';require_once ROOT_PATH.'/security/middleware/RoleMiddleware.php';
header('Content-Type: application/json');AuthMiddleware::startSession();$me=AuthMiddleware::requireAuth(true);RoleMiddleware::requireRole(['admin','super_admin'],true);$db=Database::getInstance();
if($_SERVER['REQUEST_METHOD']==='GET'){$status=$_GET['status']??'pending';if(!in_array($status,['pending','approved','rejected','cancelled','all'],true))$status='pending';$sql="SELECT r.id,r.user_id,r.proof_original_name,r.reason,r.status,r.review_note,r.created_at,r.reviewed_at,u.username,u.full_name,u.email FROM facilitator_requests r JOIN users u ON u.id=r.user_id".($status==='all'?'':' WHERE r.status=:status')." ORDER BY r.created_at DESC";$s=$db->prepare($sql);$s->execute($status==='all'?[]:[':status'=>$status]);echo json_encode(['success'=>true,'requests'=>$s->fetchAll(PDO::FETCH_ASSOC)]);exit;}
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['success'=>false,'error'=>'Method not allowed']);exit;}AuthMiddleware::verifyCsrf();
$b=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($b['request_id']??0);$decision=(string)($b['decision']??'');$note=trim((string)($b['note']??''));
if(!$id||!in_array($decision,['approve','reject'],true)){http_response_code(422);echo json_encode(['success'=>false,'error'=>'Invalid review request.']);exit;}
$db->beginTransaction();try{$s=$db->prepare("SELECT r.*,u.role FROM facilitator_requests r JOIN users u ON u.id=r.user_id WHERE r.id=? FOR UPDATE");$s->execute([$id]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r||$r['status']!=='pending')throw new RuntimeException('Request is no longer pending.');
$newStatus=$decision==='approve'?'approved':'rejected';$db->prepare('UPDATE facilitator_requests SET status=?,reviewed_by=?,review_note=?,reviewed_at=NOW() WHERE id=?')->execute([$newStatus,$me['id'],$note?:null,$id]);
if($decision==='approve'){$old=(string)$r['role'];$db->prepare("UPDATE users SET role='facilitator' WHERE id=?")->execute([$r['user_id']]);$db->prepare("INSERT INTO role_audit_log(actor_user_id,target_user_id,action,old_role,new_role,metadata_json) VALUES(?,?, 'facilitator_request_approved',?,?,?)")->execute([$me['id'],$r['user_id'],$old,'facilitator',json_encode(['request_id'=>$id])]);}
else{$db->prepare("INSERT INTO role_audit_log(actor_user_id,target_user_id,action,old_role,new_role,metadata_json) VALUES(?,?, 'facilitator_request_rejected',?,?,?)")->execute([$me['id'],$r['user_id'],$r['role'],$r['role'],json_encode(['request_id'=>$id])]);}
$db->commit();echo json_encode(['success'=>true,'status'=>$newStatus,'user_id'=>(int)$r['user_id'],'new_role'=>$decision==='approve'?'facilitator':$r['role']]);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();http_response_code(409);echo json_encode(['success'=>false,'error'=>$e->getMessage()]);}
