<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once ROOT_PATH.'/database/config/db.php';require_once ROOT_PATH.'/security/middleware/AuthMiddleware.php';require_once ROOT_PATH.'/security/middleware/RoleMiddleware.php';
header('Content-Type: application/json');AuthMiddleware::startSession();$me=AuthMiddleware::requireAuth(true);RoleMiddleware::requireRole(['admin','super_admin'],true);
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['success'=>false,'error'=>'POST required']);exit;}AuthMiddleware::verifyCsrf();
$b=json_decode(file_get_contents('php://input'),true)?:[];$topic=trim((string)($b['topic']??''));$task=trim((string)($b['task']??''));$size=max(2,min(8,(int)($b['group_size']??4)));if($topic===''&&$task===''){http_response_code(422);echo json_encode(['success'=>false,'error'=>'Topic or task is required']);exit;}
$db=Database::getInstance();$cols=[];foreach($db->query('SHOW COLUMNS FROM user_profiles')->fetchAll(PDO::FETCH_ASSOC) as $r)$cols[$r['Field']]=true;$wanted=['bio','program','year_level','study_style','study_goal','goals','interests','hobbies','skills','strengths','weaknesses'];$select=[];foreach($wanted as $c)if(isset($cols[$c]))$select[]="up.`$c`";
$sql="SELECT u.id,u.username,u.full_name,u.role".($select?','.implode(',',$select):'')." FROM users u LEFT JOIN user_profiles up ON up.user_id=u.id WHERE u.deleted_at IS NULL AND u.status='active' AND u.role IN ('student','facilitator') ORDER BY u.id DESC LIMIT 80";$users=$db->query($sql)->fetchAll(PDO::FETCH_ASSOC);
if(count($users)<2){echo json_encode(['success'=>true,'source'=>'database','groups'=>[],'message'=>'Not enough active users with profiles to recommend a group.']);exit;}
$profiles=[];foreach($users as $u){$bits=[];foreach($u as $k=>$v)if(!in_array($k,['id','username','full_name','role'],true)&&$v!==null&&$v!=='')$bits[]="$k: $v";$profiles[]=['id'=>(int)$u['id'],'username'=>$u['username'],'name'=>$u['full_name']?:$u['username'],'role'=>$u['role'],'profile'=>implode('; ',$bits)];}
$ollama=rtrim((string)env('OLLAMA_URL','http://127.0.0.1:11434'),'/');$model=(string)env('OLLAMA_MODEL','qwen3:1.7b');$prompt="You are Ecollab's peer-group recommender. Use ONLY the supplied real users. Recommend balanced groups for the topic/task. Return strict JSON only: {\"groups\":[{\"reason\":\"...\",\"members\":[{\"id\":1,\"username\":\"...\",\"role\":\"...\",\"fit\":\"...\"}]}]}. Never invent a user or ID. Group size: $size. Topic: $topic. Task: $task. Users: ".json_encode($profiles,JSON_UNESCAPED_UNICODE);
$payload=json_encode(['model'=>$model,'stream'=>false,'format'=>'json','messages'=>[['role'=>'user','content'=>$prompt]],'options'=>['temperature'=>0.2]]);
$ch=curl_init($ollama.'/api/chat');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>2,CURLOPT_TIMEOUT=>45,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>$payload]);$raw=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);
if($raw===false||$code<200||$code>=300){http_response_code(503);echo json_encode(['success'=>false,'error'=>'Local LLM unavailable','detail'=>APP_DEBUG?$err:null,'model'=>$model]);exit;}$outer=json_decode($raw,true);$content=$outer['message']['content']??'';$parsed=json_decode($content,true);if(!is_array($parsed)){http_response_code(502);echo json_encode(['success'=>false,'error'=>'Local LLM returned invalid JSON','model'=>$model]);exit;}
$allowed=[];foreach($profiles as $p)$allowed[$p['id']]=$p;$groups=[];foreach(($parsed['groups']??[]) as $g){$members=[];foreach(($g['members']??[]) as $m){$id=(int)($m['id']??0);if(isset($allowed[$id]))$members[]=['id'=>$id,'username'=>$allowed[$id]['username'],'name'=>$allowed[$id]['name'],'role'=>$allowed[$id]['role'],'fit'=>trim((string)($m['fit']??''))];}if(count($members)>=2)$groups[]=['reason'=>trim((string)($g['reason']??'')),'members'=>$members];}
echo json_encode(['success'=>true,'source'=>'local_llm','model'=>$model,'topic'=>$topic,'task'=>$task,'groups'=>$groups,'candidate_count'=>count($profiles)]);
