<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once ROOT_PATH.'/database/config/db.php';require_once ROOT_PATH.'/security/middleware/AuthMiddleware.php';
AuthMiddleware::startSession();$user=AuthMiddleware::requireAuth(true);header('Content-Type: application/json; charset=utf-8');$db=Database::getInstance();$uid=(int)$user['id'];
function msJson(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
try{$owned=[];$shared=[];
$q=$db->prepare('SELECT d.id,d.title,d.file_name,d.file_type,d.workspace_id,d.visibility,d.public_permission,d.created_by,COALESCE(NULLIF(u.full_name,""),u.username) owner_name FROM collab_documents d LEFT JOIN users u ON u.id=d.created_by WHERE d.created_by=:uid AND d.visibility="private" ORDER BY d.updated_at DESC,d.id DESC');$q->execute([':uid'=>$uid]);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r){$r['resource_type']='document';$r['open_url']=BASE_URL.'/modules/collaboration/document.php?id='.(int)$r['id'].'&workspace_id='.(int)$r['workspace_id'];$owned[]=$r;}
$q=$db->prepare('SELECT w.id,w.title,w.description,w.workspace_id,w.visibility,w.public_permission,w.created_by,COALESCE(NULLIF(u.full_name,""),u.username) owner_name FROM collab_whiteboards w LEFT JOIN users u ON u.id=w.created_by WHERE w.created_by=:uid AND w.visibility="private" ORDER BY w.updated_at DESC,w.id DESC');$q->execute([':uid'=>$uid]);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r){$r['resource_type']='whiteboard';$r['open_url']=BASE_URL.'/modules/whiteboard/session.php?workspace_id='.(int)$r['workspace_id'].'&whiteboard_id='.(int)$r['id'];$owned[]=$r;}
$q=$db->prepare('SELECT p.resource_id,p.permission,p.workspace_id,COALESCE(NULLIF(u.full_name,""),u.username) owner_name,d.title,d.file_name,d.file_type,d.visibility,d.public_permission FROM collab_resource_permissions p INNER JOIN collab_documents d ON d.id=p.resource_id AND d.workspace_id=p.workspace_id INNER JOIN users u ON u.id=d.created_by WHERE p.resource_type="document" AND p.user_id=:uid AND d.visibility="private" AND d.created_by<>:uid ORDER BY d.updated_at DESC');$q->execute([':uid'=>$uid]);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r){$r['resource_type']='document';$r['open_url']=BASE_URL.'/modules/collaboration/document.php?id='.(int)$r['resource_id'].'&workspace_id='.(int)$r['workspace_id'];$shared[]=$r;}
$q=$db->prepare('SELECT p.resource_id,p.permission,p.workspace_id,COALESCE(NULLIF(u.full_name,""),u.username) owner_name,w.title,w.description,w.visibility,w.public_permission FROM collab_resource_permissions p INNER JOIN collab_whiteboards w ON w.id=p.resource_id AND w.workspace_id=p.workspace_id INNER JOIN users u ON u.id=w.created_by WHERE p.resource_type="whiteboard" AND p.user_id=:uid AND w.visibility="private" AND w.created_by<>:uid ORDER BY w.updated_at DESC');$q->execute([':uid'=>$uid]);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r){$r['resource_type']='whiteboard';$r['open_url']=BASE_URL.'/modules/whiteboard/session.php?workspace_id='.(int)$r['workspace_id'].'&whiteboard_id='.(int)$r['resource_id'];$shared[]=$r;}
msJson(['success'=>true,'owned'=>$owned,'shared'=>$shared]);}catch(Throwable $e){error_log('[my-space] '.$e->getMessage());msJson(['success'=>false,'error'=>'Unable to load My Space.'],500);}
