<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/config.php';require_once ROOT_PATH.'/database/config/db.php';require_once ROOT_PATH.'/security/middleware/AuthMiddleware.php';require_once ROOT_PATH.'/services/CoworkspaceService.php';AuthMiddleware::startSession();$user=AuthMiddleware::requireAuth(true);header('Content-Type: application/json; charset=utf-8');$db=Database::getInstance();$uid=(int)$user['id'];
function raJson(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function raInput():array{$x=json_decode(file_get_contents('php://input'),true);return is_array($x)?$x:$_POST;}function raPermission(mixed $p):string{$p=strtolower(trim((string)$p));return in_array($p,['view','comment','edit'],true)?$p:'view';}function raResource(PDO $db,int $wid,string $type,int $rid):array{if(!in_array($type,['document','whiteboard'],true)||$rid<1)raJson(['success'=>false,'error'=>'Invalid resource.'],400);$table=$type==='document'?'collab_documents':'collab_whiteboards';$s=$db->prepare("SELECT id,workspace_id,created_by,visibility,public_permission,title FROM {$table} WHERE id=:id AND workspace_id=:wid LIMIT 1");$s->execute([':id'=>$rid,':wid'=>$wid]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)raJson(['success'=>false,'error'=>'Resource not found.'],404);return $r;}
try{$method=strtoupper($_SERVER['REQUEST_METHOD']??'GET');$data=$method==='GET'?$_GET:raInput();$wid=(int)($data['workspace_id']??0);$type=strtolower(trim((string)($data['resource_type']??'')));$rid=(int)($data['resource_id']??0);$workspace=CoworkspaceService::get($db,$wid,$uid,true);
if($method==='GET'&&(($data['action']??'')==='users')){$q=trim((string)($data['q']??''));if($q==='')raJson(['success'=>true,'users'=>[]]);$s=$db->prepare('SELECT u.id,COALESCE(NULLIF(u.full_name,""),u.username) name,u.username FROM users u INNER JOIN server_members sm ON sm.user_id=u.id AND sm.server_id=:sid WHERE (u.username LIKE :q1 OR u.full_name LIKE :q2) AND u.id<>:uid ORDER BY name LIMIT 20');$needle='%'.$q.'%';$s->execute([':sid'=>(int)$workspace['server_id'],':q1'=>$needle,':q2'=>$needle,':uid'=>$uid]);raJson(['success'=>true,'users'=>array_map(fn($x)=>['id'=>(int)$x['id'],'name'=>$x['name'],'username'=>$x['username']],$s->fetchAll(PDO::FETCH_ASSOC))]);}
$r=raResource($db,$wid,$type,$rid);$isOwner=(int)$r['created_by']===$uid||(int)$workspace['host_id']===$uid;$pstmt=$db->prepare('SELECT permission FROM collab_resource_permissions WHERE resource_type=:t AND resource_id=:rid AND user_id=:uid LIMIT 1');$pstmt->execute([':t'=>$type,':rid'=>$rid,':uid'=>$uid]);$myPerm=$pstmt->fetchColumn();if($myPerm!==false)$myPerm=raPermission($myPerm);if(!$isOwner&&$r['visibility']==='private'&&$myPerm===false)raJson(['success'=>false,'error'=>'This private resource has not been shared with you.'],403);
if($method==='GET'){$s=$db->prepare('SELECT p.user_id,p.permission,COALESCE(NULLIF(u.full_name,""),u.username) name,u.username FROM collab_resource_permissions p INNER JOIN users u ON u.id=p.user_id WHERE p.resource_type=:t AND p.resource_id=:rid ORDER BY name');$s->execute([':t'=>$type,':rid'=>$rid]);$permissions=array_map(fn($x)=>['user_id'=>(int)$x['user_id'],'permission'=>raPermission($x['permission']),'name'=>$x['name'],'username'=>$x['username']],$s->fetchAll(PDO::FETCH_ASSOC));$i=$db->prepare('SELECT id,permission,expires_at,revoked_at,created_at FROM collab_resource_invites WHERE resource_type=:t AND resource_id=:rid ORDER BY id DESC');$i->execute([':t'=>$type,':rid'=>$rid]);$invites=array_map(fn($x)=>['id'=>(int)$x['id'],'permission'=>raPermission($x['permission']),'expires_at'=>$x['expires_at'],'revoked_at'=>$x['revoked_at'],'created_at'=>$x['created_at']],$i->fetchAll(PDO::FETCH_ASSOC));$public=raPermission($r['public_permission']??'view');raJson(['success'=>true,'resource'=>['id'=>$rid,'type'=>$type,'title'=>$r['title'],'visibility'=>$r['visibility'],'public_permission'=>$public,'owner_id'=>(int)$r['created_by']],'my_permission'=>$isOwner?'edit':($myPerm!==false?$myPerm:($r['visibility']==='public'?$public:null)),'can_manage'=>$isOwner,'permissions'=>$permissions,'invites'=>$invites]);}
if($method!=='POST')raJson(['success'=>false,'error'=>'Method not allowed.'],405);AuthMiddleware::verifyCsrf();if(!$isOwner)raJson(['success'=>false,'error'=>'Only the resource owner or Coworkspace host can manage access.'],403);$action=strtolower(trim((string)($data['action']??'')));$table=$type==='document'?'collab_documents':'collab_whiteboards';
if($action==='set_visibility'){$v=strtolower((string)($data['visibility']??''));if(!in_array($v,['public','private'],true))raJson(['success'=>false,'error'=>'Visibility must be public or private.'],400);$db->prepare("UPDATE {$table} SET visibility=:v WHERE id=:id AND workspace_id=:wid")->execute([':v'=>$v,':id'=>$rid,':wid'=>$wid]);raJson(['success'=>true,'visibility'=>$v]);}
if($action==='set_public_permission'){$p=raPermission($data['permission']??'view');$db->prepare("UPDATE {$table} SET public_permission=:p WHERE id=:id AND workspace_id=:wid")->execute([':p'=>$p,':id'=>$rid,':wid'=>$wid]);raJson(['success'=>true,'public_permission'=>$p]);}
if($action==='grant'){$target=(int)($data['user_id']??0);$p=raPermission($data['permission']??'view');if($target<1)raJson(['success'=>false,'error'=>'A user is required.'],400);$s=$db->prepare('SELECT 1 FROM server_members WHERE server_id=:sid AND user_id=:uid LIMIT 1');$s->execute([':sid'=>(int)$workspace['server_id'],':uid'=>$target]);if(!$s->fetchColumn())raJson(['success'=>false,'error'=>'User is not a member of this server.'],400);$db->prepare('INSERT INTO collab_resource_permissions(resource_type,resource_id,workspace_id,user_id,permission,granted_by) VALUES(:t,:rid,:wid,:uid,:p,:by) ON DUPLICATE KEY UPDATE permission=VALUES(permission),granted_by=VALUES(granted_by),updated_at=CURRENT_TIMESTAMP')->execute([':t'=>$type,':rid'=>$rid,':wid'=>$wid,':uid'=>$target,':p'=>$p,':by'=>$uid]);raJson(['success'=>true,'permission'=>$p]);}
if($action==='revoke'){$target=(int)($data['user_id']??0);$db->prepare('DELETE FROM collab_resource_permissions WHERE resource_type=:t AND resource_id=:rid AND user_id=:uid')->execute([':t'=>$type,':rid'=>$rid,':uid'=>$target]);raJson(['success'=>true]);}
if($action==='invite'){$p=raPermission($data['permission']??'view');$raw=bin2hex(random_bytes(24));$exp=trim((string)($data['expires_at']??''));$expires=$exp!==''?date('Y-m-d H:i:s',strtotime($exp)):null;$db->prepare('INSERT INTO collab_resource_invites(resource_type,resource_id,workspace_id,token_hash,permission,created_by,expires_at) VALUES(:t,:rid,:wid,:hash,:p,:by,:exp)')->execute([':t'=>$type,':rid'=>$rid,':wid'=>$wid,':hash'=>hash('sha256',$raw),':p'=>$p,':by'=>$uid,':exp'=>$expires]);raJson(['success'=>true,'url'=>BASE_URL.'/modules/collaboration/resource-invite.php?token='.rawurlencode($raw),'permission'=>$p,'expires_at'=>$expires]);}
if($action==='revoke_invite'){$invite=(int)($data['invite_id']??0);$db->prepare('UPDATE collab_resource_invites SET revoked_at=CURRENT_TIMESTAMP WHERE id=:id AND resource_type=:t AND resource_id=:rid')->execute([':id'=>$invite,':t'=>$type,':rid'=>$rid]);raJson(['success'=>true]);}raJson(['success'=>false,'error'=>'Unknown access action.'],400);
}catch(Throwable $e){error_log('[resource-access] '.$e->getMessage());raJson(['success'=>false,'error'=>'Unable to process resource access.'],500);}
