<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once ROOT_PATH.'/database/config/db.php';
require_once ROOT_PATH.'/security/middleware/AuthMiddleware.php';
header('Content-Type: application/json');
AuthMiddleware::startSession();
$user=AuthMiddleware::requireAuth(true);
if(!in_array($user['role']??'', ['facilitator','admin','super_admin','moderator'], true)){http_response_code(403);echo json_encode(['error'=>'Facilitator access required']);exit;}
$db=Database::getInstance(); $uid=(int)$user['id'];
function owned(PDO $db,int $sid,int $uid):bool{$q=$db->prepare('SELECT 1 FROM servers WHERE id=? AND owner_id=? LIMIT 1');$q->execute([$sid,$uid]);return(bool)$q->fetchColumn();}
function body():array{$b=json_decode(file_get_contents('php://input'),true);return is_array($b)?$b:$_POST;}
function announcementChannel(PDO $db,int $sid,int $uid):int{$q=$db->prepare("SELECT id FROM channels WHERE server_id=? AND (type='announcement' OR slug='announcements') ORDER BY type='announcement' DESC,id LIMIT 1");$q->execute([$sid]);$id=(int)$q->fetchColumn();if($id)return$id;$q=$db->prepare("INSERT INTO channels(server_id,name,slug,type,description,position,is_private,is_locked,created_by) VALUES(?,'announcements','announcements','announcement','Official server announcements (view only)',0,0,1,?)");$q->execute([$sid,$uid]);return(int)$db->lastInsertId();}
$method=$_SERVER['REQUEST_METHOD'];$action=(string)($_GET['action']??'servers');
if($method==='GET'){
 if($action==='servers'){$q=$db->prepare("SELECT id,name,description,type,status,member_count FROM servers WHERE owner_id=? AND status<>'archived' ORDER BY name");$q->execute([$uid]);echo json_encode(['success'=>true,'servers'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 $sid=(int)($_GET['server_id']??0);if(!$sid||!owned($db,$sid,$uid)){http_response_code(403);echo json_encode(['error'=>'You do not own this server']);exit;}
 if($action==='resources'){$q=$db->prepare("SELECT f.id,f.file_name,f.original_name,f.file_path,f.file_size,f.mime_type,f.created_at,u.username,c.name channel_name FROM uploaded_files f JOIN users u ON u.id=f.uploader_id LEFT JOIN channels c ON c.id=f.channel_id WHERE f.server_id=? AND f.deleted_at IS NULL ORDER BY f.created_at DESC");$q->execute([$sid]);echo json_encode(['success'=>true,'files'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 if($action==='activity'){$q=$db->prepare("SELECT u.id,u.username,u.full_name,COUNT(DISTINCT m.id) messages,COUNT(DISTINCT srp.id) voice_joins,COALESCE(SUM(CASE WHEN srp.joined_at IS NOT NULL THEN TIMESTAMPDIFF(SECOND,srp.joined_at,COALESCE(srp.left_at,NOW())) ELSE 0 END),0) voice_seconds,MAX(m.created_at) last_message FROM server_members sm JOIN users u ON u.id=sm.user_id LEFT JOIN channels c ON c.server_id=sm.server_id LEFT JOIN messages m ON m.channel_id=c.id AND m.sender_id=u.id AND m.is_deleted=0 LEFT JOIN study_rooms sr ON sr.server_id=sm.server_id LEFT JOIN study_room_participants srp ON srp.room_id=sr.id AND srp.user_id=u.id WHERE sm.server_id=? AND u.id<>? GROUP BY u.id,u.username,u.full_name ORDER BY messages DESC");$q->execute([$sid,$uid]);echo json_encode(['success'=>true,'users'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 if($action==='reports'){$q=$db->prepare("SELECT r.*,ru.username reporter_username,tu.username reported_username FROM content_reports r JOIN users ru ON ru.id=r.reporter_id LEFT JOIN users tu ON tu.id=r.reported_user_id WHERE r.server_id=? ORDER BY r.created_at DESC");$q->execute([$sid]);echo json_encode(['success'=>true,'reports'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 if($action==='banned'){$q=$db->prepare("SELECT ma.id,ma.target_user_id,u.username,u.full_name,ma.reason,ma.created_at FROM moderation_actions ma JOIN users u ON u.id=ma.target_user_id WHERE ma.server_id=? AND ma.action_type='ban' AND ma.is_active=1 AND (ma.expires_at IS NULL OR ma.expires_at>NOW()) ORDER BY ma.created_at DESC");$q->execute([$sid]);echo json_encode(['success'=>true,'users'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
}
if($method!=='POST'){http_response_code(405);echo json_encode(['error'=>'Method not allowed']);exit;}
AuthMiddleware::verifyCsrf();$b=body();$sid=(int)($b['server_id']??0);if(!$sid||!owned($db,$sid,$uid)){http_response_code(403);echo json_encode(['error'=>'You can only manage servers you own']);exit;}
try{
 if($action==='announcement'){$title=trim((string)($b['title']??''));$message=trim((string)($b['message']??''));if($title===''||$message===''){throw new InvalidArgumentException('Title and message are required');}$db->beginTransaction();$cid=announcementChannel($db,$sid,$uid);$text="📢 ".$title."\n\n".$message;$q=$db->prepare("INSERT INTO messages(channel_id,sender_id,content,content_type) VALUES(?,?,?,'text')");$q->execute([$cid,$uid,$text]);$link=(defined('BASE_URL')?BASE_URL:'').'/modules/chat/chat.php?server_id='.$sid.'&channel_id='.$cid;$q=$db->prepare("INSERT INTO notifications(recipient_id,actor_id,type,title,body,link_url,icon) SELECT sm.user_id,?,'class_update',?,?,?,'📢' FROM server_members sm WHERE sm.server_id=? AND sm.user_id<>?");$q->execute([$uid,$title,$message,$link,$sid,$uid]);$db->commit();echo json_encode(['success'=>true,'channel_id'=>$cid]);exit;}
 if($action==='settings'){$name=trim((string)($b['name']??''));$desc=trim((string)($b['description']??''));$visibility=(string)($b['visibility']??'private');$locked=!empty($b['lock_channels'])?1:0;if($name==='')throw new InvalidArgumentException('Server name is required');$cols=[];foreach($db->query('SHOW COLUMNS FROM servers')->fetchAll(PDO::FETCH_ASSOC) as $r)$cols[$r['Field']]=true;$sets=['name=?','description=?'];$p=[$name,$desc];if(isset($cols['visibility'])){$sets[]='visibility=?';$p[]=$visibility;}elseif(isset($cols['type'])){$sets[]='type=?';$p[]=$visibility==='public'?'public':'private';}$p[]=$sid;$db->prepare('UPDATE servers SET '.implode(',',$sets).' WHERE id=?')->execute($p);$db->prepare('UPDATE channels SET is_locked=? WHERE server_id=? AND type<>\'announcement\'')->execute([$locked,$sid]);announcementChannel($db,$sid,$uid);echo json_encode(['success'=>true]);exit;}
 if($action==='moderate'){$target=(int)($b['target_user_id']??0);$kind=(string)($b['kind']??'');if(!in_array($kind,['mute','kick','ban','unmute','unban'],true)||!$target)throw new InvalidArgumentException('Invalid moderation action');$reason=trim((string)($b['reason']??''));$mins=isset($b['duration_mins'])?(int)$b['duration_mins']:null;$expires=$mins?date('Y-m-d H:i:s',time()+$mins*60):null;$db->prepare("INSERT INTO moderation_actions(moderator_id,target_user_id,server_id,action_type,reason,duration_mins,expires_at,is_active) VALUES(?,?,?,?,?,?,?,1)")->execute([$uid,$target,$sid,$kind,$reason,$mins,$expires]);if($kind==='kick'||$kind==='ban')$db->prepare('DELETE FROM server_members WHERE server_id=? AND user_id=?')->execute([$sid,$target]);if($kind==='unban')$db->prepare("UPDATE moderation_actions SET is_active=0 WHERE server_id=? AND target_user_id=? AND action_type='ban'")->execute([$sid,$target]);echo json_encode(['success'=>true]);exit;}
 http_response_code(400);echo json_encode(['error'=>'Unknown action']);
}catch(InvalidArgumentException $e){if($db->inTransaction())$db->rollBack();http_response_code(422);echo json_encode(['error'=>$e->getMessage()]);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('[facilitator server-tools] '.$e->getMessage());http_response_code(500);echo json_encode(['error'=>'Unable to complete request']);}
