<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once ROOT_PATH.'/database/config/db.php';
require_once ROOT_PATH.'/security/middleware/AuthMiddleware.php';
header('Content-Type: application/json');
AuthMiddleware::startSession();
$user=AuthMiddleware::requireAuth(true);
if(!in_array($user['role']??'', ['facilitator','admin','super_admin','moderator'], true)){http_response_code(403);echo json_encode(['error'=>'Facilitator access required']);exit;}
$db=Database::getInstance(); $uid=(int)$user['id'];
function owned(PDO $db,int $sid,int $uid):bool{$q=$db->prepare('SELECT 1 FROM servers WHERE id=? AND owner_id=? LIMIT 1');$q->execute([$sid,$uid]);return(bool)$q->fetchColumn();}
function body():array{$b=json_decode(file_get_contents('php://input'),true);return is_array($b)?$b:$_POST;}
function announcementChannel(PDO $db,int $sid,int $uid):int{$q=$db->prepare("SELECT id FROM channels WHERE server_id=? AND (type='announcement' OR slug='announcements') ORDER BY type='announcement' DESC,id LIMIT 1");$q->execute([$sid]);$id=(int)$q->fetchColumn();if($id)return$id;$q=$db->prepare("INSERT INTO channels(server_id,name,slug,type,description,position,is_private,is_locked,created_by) VALUES(?,'announcements','announcements','announcement','Official server announcements (view only)',0,0,1,?)");$q->execute([$sid,$uid]);return(int)$db->lastInsertId();}
$method=$_SERVER['REQUEST_METHOD'];$action=(string)($_GET['action']??'servers');
if($method==='GET'){
 if($action==='servers'){$q=$db->prepare("SELECT id,name,description,type,status,member_count FROM servers WHERE owner_id=? AND status<>'archived' ORDER BY name");$q->execute([$uid]);echo json_encode(['success'=>true,'servers'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 $sid=(int)($_GET['server_id']??0);if(!$sid||!owned($db,$sid,$uid)){http_response_code(403);echo json_encode(['error'=>'You do not own this server']);exit;}
 if($action==='announcements'){$q=$db->prepare("SELECT m.id,m.content,m.created_at,m.sender_id,c.id channel_id,c.name channel_name,COALESCE(u.full_name,u.username) author_name FROM messages m JOIN channels c ON c.id=m.channel_id LEFT JOIN users u ON u.id=m.sender_id WHERE c.server_id=? AND (c.type='announcement' OR c.slug='announcements' OR c.name='announcements') AND m.is_deleted=0 ORDER BY m.created_at DESC LIMIT 100");$q->execute([$sid]);echo json_encode(['success'=>true,'announcements'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 if($action==='permissions'){$q=$db->prepare("SELECT s.id,s.name,COALESCE(fp.allow_member_invites,1) allow_member_invites,COALESCE(fp.allow_member_messages,1) allow_member_messages,COALESCE(fp.allow_voice,1) allow_voice,COALESCE(fp.allow_polls,1) allow_polls,COALESCE(fp.allow_files,1) allow_files FROM servers s LEFT JOIN facilitator_server_permissions fp ON fp.server_id=s.id WHERE s.id=? AND s.owner_id=?");$q->execute([$sid,$uid]);echo json_encode(['success'=>true,'permissions'=>$q->fetch(PDO::FETCH_ASSOC)]);exit;}
 if($action==='resources'){$q=$db->prepare("SELECT f.id,f.file_name,f.original_name,f.file_path,f.file_size,f.mime_type,f.created_at,u.username,c.name channel_name FROM uploaded_files f JOIN users u ON u.id=f.uploader_id LEFT JOIN channels c ON c.id=f.channel_id WHERE f.server_id=? AND f.deleted_at IS NULL ORDER BY f.created_at DESC");$q->execute([$sid]);echo json_encode(['success'=>true,'files'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 if($action==='workspace'){try{$q=$db->prepare("SELECT d.id,'document' item_type,d.title item_name,d.updated_at created_at,d.visibility,w.channel_id,c.name channel_name FROM collab_documents d JOIN collab_workspaces w ON w.id=d.workspace_id LEFT JOIN channels c ON c.id=w.channel_id WHERE w.server_id=? AND d.visibility='public' UNION ALL SELECT b.id,'whiteboard',b.title,b.updated_at,b.visibility,w2.channel_id,c2.name FROM collab_whiteboards b JOIN collab_workspaces w2 ON w2.id=b.workspace_id LEFT JOIN channels c2 ON c2.id=w2.channel_id WHERE w2.server_id=? AND b.visibility='public' ORDER BY created_at DESC");$q->execute([$sid,$sid]);echo json_encode(['success'=>true,'items'=>$q->fetchAll(PDO::FETCH_ASSOC)]);}catch(Throwable $e){error_log('[facilitator workspace] '.$e->getMessage());echo json_encode(['success'=>true,'items'=>[]]);}exit;}
 if($action==='activity'){$q=$db->prepare("SELECT u.id,u.username,u.full_name,COUNT(DISTINCT m.id) messages,COUNT(DISTINCT srp.id) voice_joins,COALESCE(SUM(CASE WHEN srp.joined_at IS NOT NULL THEN TIMESTAMPDIFF(SECOND,srp.joined_at,COALESCE(srp.left_at,NOW())) ELSE 0 END),0) voice_seconds,MAX(m.created_at) last_message FROM server_members sm JOIN users u ON u.id=sm.user_id LEFT JOIN channels c ON c.server_id=sm.server_id LEFT JOIN messages m ON m.channel_id=c.id AND m.sender_id=u.id AND m.is_deleted=0 LEFT JOIN study_rooms sr ON sr.server_id=sm.server_id LEFT JOIN study_room_participants srp ON srp.room_id=sr.id AND srp.user_id=u.id WHERE sm.server_id=? AND u.id<>? GROUP BY u.id,u.username,u.full_name ORDER BY messages DESC");$q->execute([$sid,$uid]);echo json_encode(['success'=>true,'users'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 if($action==='reports'){$q=$db->prepare("SELECT r.*,ru.username reporter_username,COALESCE(ru.full_name,ru.username) reporter_name,tu.username reported_username,COALESCE(tu.full_name,tu.username) reported_name,m.content message_content,c.name channel_name FROM content_reports r JOIN users ru ON ru.id=r.reporter_id LEFT JOIN users tu ON tu.id=r.reported_user_id LEFT JOIN messages m ON m.id=r.message_id LEFT JOIN channels c ON c.id=m.channel_id WHERE r.server_id=? ORDER BY FIELD(r.status,'pending','reviewing','resolved','dismissed'),r.created_at DESC");$q->execute([$sid]);echo json_encode(['success'=>true,'reports'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
 if($action==='banned'){$q=$db->prepare("SELECT ma.id,ma.target_user_id,u.username,u.full_name,ma.reason,ma.created_at FROM moderation_actions ma JOIN users u ON u.id=ma.target_user_id WHERE ma.server_id=? AND ma.action_type='ban' AND ma.is_active=1 AND (ma.expires_at IS NULL OR ma.expires_at>NOW()) ORDER BY ma.created_at DESC");$q->execute([$sid]);echo json_encode(['success'=>true,'users'=>$q->fetchAll(PDO::FETCH_ASSOC)]);exit;}
}
if($method!=='POST'){http_response_code(405);echo json_encode(['error'=>'Method not allowed']);exit;}
AuthMiddleware::verifyCsrf();$b=body();$sid=(int)($b['server_id']??0);if(!$sid||!owned($db,$sid,$uid)){http_response_code(403);echo json_encode(['error'=>'You can only manage servers you own']);exit;}
try{
 if($action==='permissions'){$scope=(string)($b['apply_scope']??'server');$vals=[!empty($b['allow_member_invites'])?1:0,!empty($b['allow_member_messages'])?1:0,!empty($b['allow_voice'])?1:0,!empty($b['allow_polls'])?1:0,!empty($b['allow_files'])?1:0];$targets=[$sid];if($scope==='all'){$q=$db->prepare("SELECT id FROM servers WHERE owner_id=? AND status<>'archived'");$q->execute([$uid]);$targets=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));}$q=$db->prepare("INSERT INTO facilitator_server_permissions(server_id,allow_member_invites,allow_member_messages,allow_voice,allow_polls,allow_files,updated_by) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE allow_member_invites=VALUES(allow_member_invites),allow_member_messages=VALUES(allow_member_messages),allow_voice=VALUES(allow_voice),allow_polls=VALUES(allow_polls),allow_files=VALUES(allow_files),updated_by=VALUES(updated_by),updated_at=CURRENT_TIMESTAMP");foreach($targets as $target){if(!owned($db,$target,$uid))continue;$q->execute([$target,...$vals,$uid]);}echo json_encode(['success'=>true,'updated_servers'=>count($targets)]);exit;}
 if($action==='announcement'){$title=trim((string)($b['title']??''));$message=trim((string)($b['message']??''));if($title===''||$message===''){throw new InvalidArgumentException('Title and message are required');}$db->beginTransaction();$cid=announcementChannel($db,$sid,$uid);$text="📢 ".$title."\n\n".$message;$q=$db->prepare("INSERT INTO messages(channel_id,sender_id,content,content_type) VALUES(?,?,?,'text')");$q->execute([$cid,$uid,$text]);$link=(defined('BASE_URL')?BASE_URL:'').'/modules/chat/chat.php?server_id='.$sid.'&channel_id='.$cid;$q=$db->prepare("INSERT INTO notifications(recipient_id,actor_id,type,title,body,link_url,icon) SELECT sm.user_id,?,'class_update',?,?,?,'📢' FROM server_members sm WHERE sm.server_id=? AND sm.user_id<>?");$q->execute([$uid,$title,$message,$link,$sid,$uid]);$db->commit();echo json_encode(['success'=>true,'channel_id'=>$cid]);exit;}
 if($action==='settings'){$name=trim((string)($b['name']??''));$desc=trim((string)($b['description']??''));$visibility=(string)($b['visibility']??'private');$locked=!empty($b['lock_channels'])?1:0;if($name==='')throw new InvalidArgumentException('Server name is required');$cols=[];foreach($db->query('SHOW COLUMNS FROM servers')->fetchAll(PDO::FETCH_ASSOC) as $r)$cols[$r['Field']]=true;$sets=['name=?','description=?'];$p=[$name,$desc];if(isset($cols['visibility'])){$sets[]='visibility=?';$p[]=$visibility;}elseif(isset($cols['type'])){$sets[]='type=?';$p[]=$visibility==='public'?'public':'private';}$p[]=$sid;$db->prepare('UPDATE servers SET '.implode(',',$sets).' WHERE id=?')->execute($p);$db->prepare('UPDATE channels SET is_locked=? WHERE server_id=? AND type<>\'announcement\'')->execute([$locked,$sid]);announcementChannel($db,$sid,$uid);echo json_encode(['success'=>true]);exit;}
 if($action==='moderate'){$target=(int)($b['target_user_id']??0);$kind=(string)($b['kind']??'');if(!in_array($kind,['mute','suspend','kick','ban','unmute','unsuspend','unban'],true)||!$target)throw new InvalidArgumentException('Invalid moderation action');if($target===$uid)throw new InvalidArgumentException('You cannot moderate yourself');$reason=trim((string)($b['reason']??''));$reportId=(int)($b['report_id']??0);$mins=isset($b['duration_mins'])?(int)$b['duration_mins']:null;if(in_array($kind,['mute','suspend'],true)&&!$mins)$mins=1440;$expires=$mins?date('Y-m-d H:i:s',time()+$mins*60):null;$dbKind=$kind;$tag='';$db->beginTransaction();$db->prepare("INSERT INTO moderation_actions(moderator_id,target_user_id,server_id,action_type,reason,duration_mins,expires_at,is_active) VALUES(?,?,?,?,?,?,?,1)")->execute([$uid,$target,$sid,$dbKind,$tag.$reason,$mins,$expires]);if($kind==='ban'||$kind==='kick')$db->prepare('DELETE FROM server_members WHERE server_id=? AND user_id=?')->execute([$sid,$target]);if($kind==='unban')$db->prepare("UPDATE moderation_actions SET is_active=0 WHERE server_id=? AND target_user_id=? AND action_type='ban'")->execute([$sid,$target]);if($kind==='unmute')$db->prepare("UPDATE moderation_actions SET is_active=0 WHERE server_id=? AND target_user_id=? AND action_type='mute'")->execute([$sid,$target]);if($kind==='unsuspend')$db->prepare("UPDATE moderation_actions SET is_active=0 WHERE server_id=? AND target_user_id=? AND action_type='suspend'")->execute([$sid,$target]);if($reportId){$q=$db->prepare("UPDATE content_reports SET status='resolved',resolved_by=?,resolved_at=NOW(),resolution_note=? WHERE id=? AND server_id=? AND status IN ('pending','reviewing')");$q->execute([$uid,ucfirst($kind).($mins?' for '.$mins.' minutes':''),$reportId,$sid]);}$db->commit();echo json_encode(['success'=>true]);exit;}
 http_response_code(400);echo json_encode(['error'=>'Unknown action']);
}catch(InvalidArgumentException $e){if($db->inTransaction())$db->rollBack();http_response_code(422);echo json_encode(['error'=>$e->getMessage()]);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('[facilitator server-tools] '.$e->getMessage());http_response_code(500);echo json_encode(['error'=>'Unable to complete request']);}
